// Mocks generated by Mockito 5.4.6 from annotations
// in my_portfolio/test/features/blog_detail/blog_detail_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_portfolio/core/error/failures.dart' as _i5;
import 'package:my_portfolio/core/services/app_launch_service.dart' as _i8;
import 'package:my_portfolio/features/blog_detail/domain/entities/blog_comment_entity.dart'
    as _i7;
import 'package:my_portfolio/features/blog_detail/domain/entities/blog_post_entity.dart'
    as _i6;
import 'package:my_portfolio/features/blog_detail/domain/repositories/blog_detail_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BlogDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlogDetailRepository extends _i1.Mock
    implements _i3.BlogDetailRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.BlogPostEntity>> getBlogPostBySlug(
    String? slug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBlogPostBySlug, [slug]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.BlogPostEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.BlogPostEntity>(
                    this,
                    Invocation.method(#getBlogPostBySlug, [slug]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.BlogPostEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.BlogPostEntity>(
                    this,
                    Invocation.method(#getBlogPostBySlug, [slug]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.BlogPostEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> recordPostRead(
    _i6.BlogPostEntity? post,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordPostRead, [post]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#recordPostRead, [post]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>(
                    this,
                    Invocation.method(#recordPostRead, [post]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> likePost(
    _i6.BlogPostEntity? post,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [post]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#likePost, [post]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither_0<_i5.Failure, bool>(
                    this,
                    Invocation.method(#likePost, [post]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.BlogCommentEntity>>> getComments(
    String? postId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.BlogCommentEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.BlogCommentEntity>>(
                    this,
                    Invocation.method(#getComments, [postId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.BlogCommentEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.BlogCommentEntity>>(
                    this,
                    Invocation.method(#getComments, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.BlogCommentEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addComment({
    required String? postId,
    required String? authorName,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [], {
              #postId: postId,
              #authorName: authorName,
              #message: message,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addComment, [], {
                  #postId: postId,
                  #authorName: authorName,
                  #message: message,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#addComment, [], {
                      #postId: postId,
                      #authorName: authorName,
                      #message: message,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [AppLaunchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLaunchService extends _i1.Mock implements _i8.AppLaunchService {
  @override
  _i4.Future<void> openExternalUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#openExternalUrl, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
